oneplus: power: wlchg: fix unused function
../drivers/oneplus/power/supply/wlchg/bq2597x_charger.c:377:12: error: unused function 'bq2597x_set_wdt' [-Werror,-Wunused-function]
static int bq2597x_set_wdt(struct bq2597x *bq, int ms)
           ^
1 error generated.

Signed-off-by: FraSharp <s23265@iisve.it>