fs: kernfs: fix unused variable
../fs/kernfs/file.c:289:7: error: unused variable 'stack_buf' [-Werror,-Wunused-variable]
        char stack_buf[PATH_MAX + 1];
             ^
1 error generated.

Signed-off-by: FraSharp <s23265@iisve.it>